import type { Middleware } from '@reduxjs/toolkit';
import { addEvent } from './db';
import { syncManager } from './sync-manager';

export const syncMiddleware: Middleware = store => next => action => {
    // Check if action is interesting
    if ((action as any).type === 'eventLog/appendEvent') {
        // This is a local action generated by the user
        // We want to persist it to DB as pending
        const state = store.getState();
        // @ts-ignore
        if (state.config.isReadOnly) {
            console.warn('Blocked write action in Read-Only mode');
            return;
        }

        const event = (action as any).payload;

        // Fire and forget persistence + sync check
        addEvent(event).then(() => {
            // Trigger sync (debouncing could be handled inside syncManager or here)
            syncManager.sync();
        }).catch(err => {
            console.error("Failed to persist event to IDB:", err);
        });
    }

    return next(action);
};
